services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    #  - redis

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_tracker
    ports:
      - "5432:5432"
  #redis:
  #  image: redis:7-alpine
  #  ports:
  #    - "6379:6379"

  #celery_worker:
  #  build: .
  #  command: celery -A app.workers.celery_app worker --loglevel=info
  #  volumes:
  #    - .:/app
  #  env_file:
  #    - .env
  #  depends_on:
  #    - db
  #    - redis

  #celery_beat:
  #  build: .
  #  command: celery -A app.workers.celery_app beat --loglevel=info
  #  volumes:
  #    - .:/app
  #  env_file:
  #    - .env
  #  depends_on:
  #    - db
  #    - redis

volumes:
  postgres_data:
